### ISSUE TITLE
Documentation wrong for running media-node as container

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-media-node#19]
`docker run -p 3000:3000 -p 40000-40249:40000-40249/udp -p 40000-40249:40000-40249/tcp user/edumeet-media-node --ip <public-ip-of-host> --secret <secret-shared-with-room-server>` will not work since you will not be able to bind to the host IP inside container.

`ERROR:MediaNode MediaService creation failed: Error: port bind failed due to address not available [transport:udp, ip:'192.168.1.249', port:40057, attempt:1/250]`

Perhaps we should suggest `--network=host` instead.

Mediasoup documentation for running on hosts with private ips
https://mediasoup.org/faq/#running-mediasoup-in-hosts-with-private-ip

**Comment by pnts-se** [comment]
@misi Would you suggest changing docs to use host networking?

**Comment by havfo** [comment]
I run with host networking. Easiest that way :+1:

**Comment by pnts-se** [comment]
@havfo me too. Go with host networking in readme.md?
