### ISSUE TITLE
[BUG] Room with same name on multiple room-server services causes crash

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-media-node#22]
When multiple room-server services use the same media-node service, rooms created with the same name will generate problems. The router generated will have the same id, so multiple room-server services will share the same router on the media-node. When the last participant leaves on one of the room-server services, requests related to the room on the other room-server service causes media-node to crash:

`edumeet:ERROR:RoomServerConnection notification() [error: Error: router with id "45547808-5847-4050-8a04-c1d7210e65b1" not found at middleware (/usr/src/app/dist/middlewares/transportMiddleware.js:136:27)`

**Comment by havfo** [comment]
Fixed in https://github.com/edumeet/edumeet-room-server/commit/acbcc32e5fd24c3cb798c862bac712f57ffbfad7
